server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activity?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Activiti 配置
  activiti:
    database-schema-update: true
    history-level: full
    db-history-used: true